### PR TITLE
#161966610 CRUD for Article

### PR DESCRIPTION
**Pull request by SnyderMbishai**
### What does this pull request do?
 This PR implements the CRUD methods for articles.
### Description of the tasks to be completed?
- create article
  ` POST /api/articles/`
- get article
  ` GET /api/articles/<slug>`
- get articles
   ` GET /api/articles/`
- update articles
  ` PUT /api/articles/<slug>`
- delete articles
  ` DELETE /api/articles/<slug>`

- test the above functionalities

### How should this be manually tested?
       $ git clone https://github.com/andela/ah-technocrats.git
       $ cd ah-technocrats
       $ git checkout ft-create-articles-161966610
       $ python3 -m venv venv
       $ source venv/bin/activate
       $ pip install -r requirements.txt
       $ python manage.py makemigrations
       $ python manage.py migrate
       $ python manage.py runserver

testing: 

       $ python manage.py test

### Screenshots:
Posting an article
image

Get all articles
image

Get a specic article using it's slug
image

Update an article
image

Delete article
image

Testsing
image
image

### What are the relevant Pivotal Tracker Stories
[#161966610](https://www.pivotaltracker.com/story/show/161966610)
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

### CODE REVIEW

**Comment by salma-nyagaka** [comment]
The PR has been documented well and the endpoints seem to be working fine

**Review by TeamoreA — COMMENTED** [review]
Looks great

**Review by verenceLola — COMMENTED** [review]
LGTM

**Review by Mnickii — APPROVED** [review]
LGTM

**Pull request merged**
