### PR TITLE
#161966623: add reading time estimation

### PR DESCRIPTION
**Pull request by TeamoreA**
### What does this pull request do?
 This PR estimates the reading time of an article.
### Description of the tasks to be completed?
- Gets the article and estimates the reading time using average human reading speed in words per minute.

### How should this be manually tested?
       $ git clone https://github.com/andela/ah-technocrats.git
       $ cd ah-technocrats
       $ git checkout ft-read-time-161966623
       $ virtualenv -p python3 env
       $ source env/bin/activate
       $ pip install -r requirements.txt
       $ python manage.py makemigrations
       $ python manage.py migrate
       $ python manage.py runserver

testing: 
       $ ./manage.py test

### Screenshots:
Show the time taken to read an article
image

### What are the relevant Pivotal Tracker Stories
[#161966623](https://www.pivotaltracker.com/story/show/161966623)
# Checklist:
- [x] My code follows the style guidelines of this project
- [ ] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

### CODE REVIEW

**Review by salma-nyagaka — COMMENTED** [review]
The reading time is okey

**Review by actlikewill — DISMISSED** [review]
Good and simple implementation. It looks okay.

**Review by SnyderMbishai — COMMENTED** [review]
Looks good. Please solve the current conflicts.

**Review by salma-nyagaka — APPROVED** [review]

**Review by SilasKenneth — APPROVED** [review]

**Review by verenceLola — APPROVED** [review]
LGTM

**Pull request merged**
