### PR TITLE
#161966629 Like and Dislike Comments

### PR DESCRIPTION
**Pull request by verenceLola**
### What does this pull request do?
 This PR implements feature to liking and disliking an article's comment
### Description of the tasks to be completed?
 - like and dislike an article's comment
To like  an article's comment, send a **POST** request to `api/comments/<comment_pk>/like/`
 - to dislike an article's comment
To dislike an article's comment , send a **POST** request to `api/articles/<article_slug>/dislike/`

NB: **this functionality is a toggle functionality. It either likes and un-likes or dislikes and un-dislikes an article's comment.**
 - to get all articles's comments
GET `api/articles/<article_slug>/comments/`
image

- test the above functionalities

### How should this be manually tested?
 - clone the repo `git clone https://github.com/andela/ah-technocrats.git`
 - change to the cloned directory `cd ah-technocrats`
 - `git checkout ft-like-comments-161966629`
 - make and activate virtual environment `python3 -m venv venv` and then `source venv/bin/activate`
 - install dependencies `pip install -r requirements.txt`
 - make Django migrations `python manage.py makemigrations`
 - migrate `python manage.py migrate`
 - finally run the server on port 8000 `python manage.py runserver`

testing automatically: 
 - run `python manage.py test` to run automatic tests

testing manually:
- the functionalities can also be manually tested using Postman on the above endpoints.

#### Getting all article's comments to see the likes and dislikes.
image

 ##### Existing article's comment ID.
image

 ##### Non existing comment ID.
image

#### Like a comment
image

#### Unlike a comment
image

 #### Dislike a comment.
image

 #### Un-dislike a comment.
image

#### Testsing
image

### What are the relevant Pivotal Tracker Stories
[#161966629](https://www.pivotaltracker.com/story/show/161966629)
# Checklist:
- [x] My code follows the style guidelines of this project
- [ ] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

### CODE REVIEW

**Review by TeamoreA — COMMENTED** [review]
LGTM

**Review by SilasKenneth — DISMISSED** [review]

**Review by SnyderMbishai — DISMISSED** [review]

**Review by actlikewill — DISMISSED** [review]
Everything looks okay, and the tests are passing.

**Review by salma-nyagaka — COMMENTED** [review]
I think for your response message, do not use Comment ID not found but rather something like comment not found

**Review by SilasKenneth — APPROVED** [review]

**Review by actlikewill — APPROVED** [review]
It looks good to me.

**Review by salma-nyagaka — APPROVED** [review]

**Pull request merged**
