### PR TITLE
#161966608  Add social authentication

### PR DESCRIPTION
**Pull request by TeamoreA**
### What does this pull request do?
 This PR allows a user to login using their social media accounts
### Description of the tasks to be completed?
- add functionality to allow Twitter, Facebook and Google login
- add settings and environment variables to facilitate this
- test the above functionalities
### How should this be manually tested?
       $ git clone https://github.com/andela/ah-technocrats.git
       $ cd ah-technocrats
       $ git checkout ft-social-auth-161966608
       $ python3 -m venv venv
       $ source venv/bin/activate
       $ pip install -r requirements.txt
 Create a `.env` file from the `.env-sample` and add the relevant environmental variables
       $ python manage.py makemigrations
       $ python manage.py migrate
       $ python manage.py runserver

Head over to postman and use `POST` method through the url `http://localhost:8000/api/social/login/`. use the following data for different providers.
Find access tokens here to use below:
[Twitter](https://developer.twitter.com/en/dashboard)
[Facebook](https://developers.facebook.com/tools/explorer/)
[Google](https://developers.google.com/oauthplayground/)

Twitter:
```
{
    "provider": "twitter",
    "access_token": "valid_access_token",
    "access_token_secret": "valid_access_token_secret"
}
```

Facebook:
```
{
    "provider":"facebook",
    "access_token":"valid_facebook_access_token"
}
```
Google:
```
{
    "provider":"google-oauth2",
    "access_token":"valid_google_access_token"
}
```

### Screenshots:
image

### What are the relevant Pivotal Tracker Stories
[#161966608](https://www.pivotaltracker.com/n/projects/2225606)
# Checklist:
- [x] My code follows the style guidelines of this project
- [ ] At least 2 people have reviewed my PR
- [x] I have used Docstrings and comments for readability
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has less than three commits.

### CODE REVIEW

**Review by verenceLola — COMMENTED** [review]
Nice work

**Review by Mnickii — DISMISSED** [review]
LGTM

**Comment by Mnickii** [comment]
Rebase

**Comment by TeamoreA** [comment]
Rebased @Mnickii

**Review by Mnickii — APPROVED** [review]
LGTM

**Pull request merged**
