### PR TITLE
#161966595 Upgrade Authors Haven Django app from Django 1.10 to Django 2.1

### PR DESCRIPTION
**Pull request by SilasKenneth**
#### What does this PR do?
Upgrades the project Django version
#### Description of Task to be completed?
Upgrade the application to use Django version 2.1 and refactor the code to conform with Django 2.1 standards
#### How should this be manually tested?
To test the application follow the steps below.
 - Clone the repo using `git clone https://github.com/andela/ah-technocrats.git`
 - ` cd ah-technocrats`
 - `git checkout ch-upgrade-project-161966595` to switch to current branch
 - run `virtualenv env -p python3` to create a virtual environment for the application
 - Activate the environment `source env/bin/activate`
 - Install required modules  using `pip install -r requirements.txt`
 - run `python manage.py test` to test
#### Any background context you want to provide?
- The project requires that you have python version 3 installed. For the Django version the project has just been tested with Django 2.1 which is the latest version as of this PR.
#### What are the relevant pivotal tracker stories?
[#161966595](https://www.pivotaltracker.com/n/projects/2225606/stories/161966595)

### CODE REVIEW

**Comment by salma-nyagaka** [comment]
Please tag reviewers to this PR

**Comment by SnyderMbishai** [comment]
Good job. Keep it up. I like that you used the recommended conventions.

**Comment by salma-nyagaka** [comment]
Change the syntax of your commit messages so that they follow the Andela way

**Comment by verenceLola** [comment]
Good work. next time please add clear steps on how to test the application. For instance, you're missing `git checkout <your-branch>`.

**Comment by TeamoreA** [comment]
The upgrade is ok. no problem encountered so far

**Comment by SilasKenneth** [comment]
@salma-nyagaka @verenceLola @SnyderMbishai @actlikewill @TeamoreA Changed the commits to follow the standards

**Comment by salma-nyagaka** [comment]
Good improvement. At least you followed the naming convention for the commit messages

**Comment by actlikewill** [comment]
Some includes in the urls files are using the old format of django 1.1

**Comment by kipropbrian** [comment]
Hi Silas, make sure to squash your commits to one.

**Comment by Mnickii** [comment]
@kipropbrian The merge will take care of the squash. @SilasKenneth In the readme i think you mean ` source env/bin/activate`

**Review by Mnickii — APPROVED** [review]
Nice work. I see you started the JWT implementation.Nice

**Review by verenceLola — APPROVED** [review]
Good work.

**Pull request merged**
