### PR TITLE
#161966606 Verify Account Through Email

### PR DESCRIPTION
**Pull request by SnyderMbishai**
### What does this pull request do?
 This PR verifies a user after a successful signup. It also activates them after the verification.
### Description of the tasks to be completed?
- add verification mail functionality
- add account activation functionality
- test the above functionalities
### How should this be manually tested?
       $ git clone https://github.com/andela/ah-technocrats.git
       $ cd ah-technocrats
       $ git checkout ft-email-verification-161966606
       $ python3 -m venv venv
       $ source venv/bin/activate
       $ pip install -r requirements.txt
       $ python manage.py makemigrations
       $ python manage.py migrate
       $ python manage.py runserver

Head over to postman and register a user throughthe url 'http://127.0.0.1:8000/api/users/'. I recommend using your own email so as to receive the message.

###### verification:
screen shot 2018-12-05 at 18 50 12

screen shot 2018-12-05 at 16 12 11

###### activation:
screen shot 2018-12-05 at 16 13 37

###### testing:
screen shot 2018-12-05 at 17 55 23

### What are the relevant Pivotal Tracker Stories
[#161966606](https://www.pivotaltracker.com/story/show/161966606)
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

### CODE REVIEW

**Comment by TeamoreA** [comment]
Looks fine your checks are passing @SnyderMbishai  .Add a new line at the end of test_mail_verification.py

**Comment by SnyderMbishai** [comment]
> Looks fine your checks are passing @SnyderMbishai .Add a new line at the end of test_mail_verification.py

Thanks. There is actually a line. Check the actual file.

**Review by Mnickii — APPROVED** [review]
LGTM

**Comment by Mnickii** [comment]
LGTM. good work!

**Pull request merged**
