### PR TITLE
#161966605 signup validation 

### PR DESCRIPTION
**Pull request by salma-nyagaka**
#### What does this PR do?
Adds descriptive validations errors to the registration functionality
#### Description of Task to be completed?
- validate email field
- validate username field
- validate the password field
#### How should this be manually tested?
- git clone https://github.com/andela/ah-technocrats.git
- cd ah-technocrats
- git checkout ft-signup-validation-161966605 
- virtualenv venv
- source venv/bin/activate
- pip install -r requirements.txt
- python manage.py makemigrations
- python manage.py migrate
- python manage.py runserver
#### Any background context you want to provide?
Users should receive a descriptive error message when they enter invalid user parameters in an attempt to signup.
#### What are the relevant pivotal tracker stories?
[#161966605](https://www.pivotaltracker.com/n/projects/2225606)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

**USERNAME WITH SPACES BETWEEN CHARACTERS**
space_between_characters

**USERNAME WITH NUMERICALS ONLY**
username_only_has_numericals

USERNAME WITH INVALID CHARACTERS
usernamewithinvalidcharacters

**SHORT USERNAME**
shortusername

**USERNAME EXISTS**
usernameexists

**PASSWORD WITH LETTERS ONLY**
passwordwithonlyletters

**SHORT PASSWORD**
shortassword

**PASSWORD WITH NO SPECIAL CHARACTER**
passwordwithnospeciacharacter

**PASSWORD WITH NUMBERS  ONLY**
passwordwithonlynumbers

### CODE REVIEW

**Comment by Mnickii** [comment]
The steps in `how should this be manually tested`
 are not sufficient

**Review by SilasKenneth — COMMENTED** [review]
Nice illustrations with screenshots

**Comment by Mnickii** [comment]
Fix the failing tests and if done, remove the WIP label. 
Very thorough screenshots. Nice!

**Review by Mnickii — APPROVED** [review]
LGTM. Nice work!

**Pull request merged**
