### PR TITLE
#161966599 Add Travis configurations

### PR DESCRIPTION
**Pull request by salma-nyagaka**
#### What does this PR do?
Integrates Travis CI to this repository
#### Description of Task to be completed?
Integrate travis CI and add the badge to README.md file
#### How should this be manually tested
- Check the README.md file for the coverall badge
#### Any background context you want to provide?
- This is required to automatically run tests and other preliminary build steps required to ship the next iteration of the product
#### What are the relevant pivotal tracker stories?
[#161966599](https://www.pivotaltracker.com/n/projects/2225606)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by SilasKenneth** [comment]
Good work @salma-nyagaka

**Review by SilasKenneth — APPROVED** [review]

**Comment by SnyderMbishai** [comment]
Please check the lines under 'script', the indentation is off there. You could also put coveralls inside requirements.txt. Otherwise, good job.

**Comment by kipropbrian** [comment]
Hey Salma, you should squash the commits into one.

**Review by Mnickii — APPROVED** [review]
Good work

**Pull request merged**
